config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root   'events#new'
   get    'home'    	    => 'events#new'
   post   'home'    	    => 'events#create'
   get    'events'  	    => 'events#index'
   get    'filtered_events' => 'events#filtered_events'
   get    'signup'  		=> 'users#new'

   resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user
	validates :username,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :events
	validates :username,  presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
	@events = Event.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
  end

  def create
  	user = User.find_by(username: params[:event][:username])

  	if user
  		event_type = params[:commit]
  		last_event = Event.where(user_id: user.id).order(created_at: :desc).first

  		if last_event.present? && last_event.event_type == event_type
  			flash.now[:danger] = "#{last_event.username} has already #{last_event.event_type} on #{last_event.created_at}"
  			render 'new'
  		elsif !last_event.present? && event_type == "Clock out"
  			flash.now[:danger] = "You cannot Clock out, Please Clock in first"
  			render 'new'
  		else 
	        @event = Event.new({
	        	username: user.username, 
	        	user_id: user.id, 
	        	event_type: event_type
	        })
	        if @event.save
	        	if last_event.present?
	        		@time_worked = (@event.created_at - last_event.created_at) / 3600
	        	end
	        	
		      	flash.now[:success] = "Success"
	      		render 'show'
		    else
		      render 'new'
		    end
		end
    else
      flash.now[:danger] = 'Invalid Username'
      render 'new'
    end
  end

  def filtered_events
  	@selected_event_type = params[:event][:event_type]
  	@selected_user = params[:event][:user_id]
  	@events = Event.where(events_params).order(created_at: :desc)
  	 				.paginate(page: params[:page], per_page: 10)
  	render action: :index
  end 

  def events_params
  	events_params = {}
    events_params[:user_id] = params[:event][:user_id] unless params[:event][:user_id] == 'all'
    events_params[:event_type] = params[:event][:event_type] unless params[:event][:event_type] == 'all'

  	return events_params
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash.now[:success] = "User successfuly created"
      redirect_to home_path
    else
      flash.now[:danger] = "Invalid Username or User already exists"
      render 'new'
    end
  end


  private

	def user_params
		params.require(:user).permit(:username, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_event.html.erb
<tr>
  <td><%= event.username %></td>
  <td><%= event.event_type %></td>
  <td><%= event.created_at %></td>
</tr>

app/views/events/index.html.erb
<% provide(:title, 'Clock Events') %>
<h1>Listing Clock Events</h1>

    <%= form_for(:event, url: filtered_events_path, html: {:method => :get}) do |f| %>
      <%= f.label :User %>
      <%= f.select :user_id, options_for_select(User.all.map{|user| [user.username, user.id]}.unshift(['All users', 'all']), 
      selected: @selected_user), class: 'form-control' %>

      <%= f.label :Event %>
      <%= f.select :event_type, options_for_select([["All events", "all"], "Clock in", "Clock out"], selected: @selected_event_type),class: 'form-control' %>

      <%= f.submit "Refresh", class: "btn btn-primary" %>
    <% end %>

<table class="table table-striped">
  <tr>
    <th>User</th>
    <th>Event</th>
    <th>Time</th>
  </tr>

   <%= render @events %>
</table>

<%= will_paginate %>

app/views/events/new.html.erb
<% provide(:title, "Home") %>
<h1>Clock in/out Platform</h1>

<div class="row">
  <div class="col-md-4 col-sm-6">

    <%= form_for(:event, url: home_path) do |f| %>
    	<div class="form-group">
		    <%= f.label :username %>
		    <%= f.text_field :username, class: 'form-control' %>
		  </div>

		  <div class="form-group">
			    <%= f.submit "Clock in", class: "btn btn-primary" %>
      		<%= f.submit "Clock out", class: "btn btn-default" %>
	  	</div>
    <% end %>

    <p>Not a user? <%= link_to "Create User", signup_path %></p>
  </div>
</div>

app/views/events/show.html.erb
<% provide(:title, "Sign in") %>
<div class='jumbotron'>

	<p>
	  <strong>User:  </strong>
	  <%= @event.username%>
	</p>
	 
	<p>
	  <strong>Event: </strong>
	  <%= @event.event_type %>
	</p>

	<p>
	  <strong>Time:  </strong>
	  <%= @event.created_at %>
	</p>

	<% if @event.event_type == "Clock out" %>
  		<p>
	  	  <strong>Time Worked: </strong>
	  	  <%= @time_worked %> Hours
		</p>
	<% end %>

	 <p class="center"><%= link_to "Ok", home_path %></p>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClockInOut</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   home_path %></li>
            <li><%= link_to "Events",   events_path %></li>
          </ul>
        </nav>
      </div>
    </header>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
<!--       <%= debug(params) if Rails.env.development? %> -->
    </div>
  </body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Create User') %>
<h1>Create User</h1>

<div class="row">
  <div class="col-md-4 col-sm-6">

    <%= form_for(@user) do |f| %>
	    <div class="form-group">
	      <%= f.label :username %>
	      <%= f.text_field :username, class: 'form-control' %>
	  	</div>

<!--       <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %> -->

		<div class="form-group">
	    	<%= f.submit "Create", class: "btn btn-primary" %>
	  	</div>
    <% end %>
  </div>
</div>